// <auto-generated />
using DeThiThu_Tutor.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeThiThu_Tutor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeThiThu_Tutor.Models.CanHo", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("DienTich")
                        .HasColumnType("float");

                    b.Property<string>("So")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToaNhaId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ToaNhaId");

                    b.ToTable("canHos");
                });

            modelBuilder.Entity("DeThiThu_Tutor.Models.ToaNha", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChhi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("toaNhas");
                });

            modelBuilder.Entity("DeThiThu_Tutor.Models.CanHo", b =>
                {
                    b.HasOne("DeThiThu_Tutor.Models.ToaNha", "ToaNha")
                        .WithMany("CanHos")
                        .HasForeignKey("ToaNhaId");

                    b.Navigation("ToaNha");
                });

            modelBuilder.Entity("DeThiThu_Tutor.Models.ToaNha", b =>
                {
                    b.Navigation("CanHos");
                });
#pragma warning restore 612, 618
        }
    }
}
